name = "emel"
version = "1.0.0"
licences = ["Apache-2.0"]
description = "Turn data into functions in the Erlang ecosystem"

[docs]
links = [
  { title = 'GitHub', href = 'https://github.com/mrdimosthenis/emel' }
]

[repository]
type = "github"
user = "mrdimosthenis"
repo = "emel"

[dependencies]
gleam_stdlib = "~> 0.22"
minigen = "~> 0.0"
gleam_zlists = "~> 0.0"
gleam_synapses = "~> 1.0"

[dev-dependencies]
gleeunit = "~> 0.6"
